# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/archetypon',
                'doc_host': 'https://schlinkertc.github.io',
                'git_url': 'https://github.com/schlinkertc/archetypon',
                'lib_path': 'archetypon'},
  'syms': {'archetypon.core': {'archetypon.core.foo': ('core.html#foo', 'archetypon/core.py')}}}
