# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/00_core.ipynb 2
from archetypon.base_model import BaseModel,DataFrame
from archetypon.record_validation import RecordFrame
import pandas as pd
